name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional PR Title
        uses: aslafy-z/conventional-pr-title-action@v3.2.0 